apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: quoters
  name: quoters
  namespace: se-tap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quoters
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quoters
    spec:
      containers:
      - image: cpingwang/quoters
        name: quoters
        resources: {}
status: {}
